import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

const s3 = new S3Client({});

/** How long the installer has to download the agent bundle. */
const DOWNLOAD_TTL_SECONDS = 24 * 60 * 60;

export type Platform = 'linux' | 'windows' | 'macos';

export const PLATFORMS: Platform[] = ['linux', 'windows', 'macos'];

export function isPlatform(value: unknown): value is Platform {
  return typeof value === 'string' && (PLATFORMS as string[]).includes(value);
}

/**
 * A presigned link to the generic agent bundle.
 *
 * The bundle lives under a `downloads/` prefix that no CloudFront behaviour
 * maps to, so it is reachable only through a link signed here — the binary is
 * not a secret, but it should not be anonymously enumerable either.
 */
async function bundleUrl(bucket: string, platform: Platform, version: string): Promise<string> {
  const extension = platform === 'windows' ? 'zip' : 'tar.gz';
  return getSignedUrl(
    s3,
    new GetObjectCommand({ Bucket: bucket, Key: `downloads/camstream-agent-${version}-${platform}.${extension}` }),
    { expiresIn: DOWNLOAD_TTL_SECONDS },
  );
}

/**
 * Builds the per-agent bootstrap script an administrator downloads.
 *
 * Deliberately tiny. Assembling a 30MB bundle per agent would exceed Lambda's
 * response limit and defeat caching of a binary that is identical for every
 * customer; instead the identity travels inline and the bundle is fetched on
 * the target machine.
 *
 * The result contains a live enrollment token, so it is a secret until used.
 */
export async function buildInstaller(
  platform: Platform,
  identity: Record<string, unknown>,
  bucket: string,
  version: string,
): Promise<{ filename: string; contentType: string; body: string }> {
  const url = await bundleUrl(bucket, platform, version);
  const thing = String(identity.thingName);
  const json = JSON.stringify(identity, null, 2);

  if (platform === 'windows') {
    return {
      filename: `install-${thing}.ps1`,
      contentType: 'text/plain; charset=utf-8',
      body: windowsScript(thing, json, url, version),
    };
  }
  return {
    filename: `install-${thing}.sh`,
    contentType: 'text/x-shellscript; charset=utf-8',
    body: posixScript(thing, json, url, version, platform),
  };
}

function posixScript(thing: string, identity: string, url: string, version: string, platform: Platform): string {
  return `#!/usr/bin/env bash
#
# CamStream agent installer for ${thing}
#
# Generated by the admin console. This file contains a single-use enrollment
# token: treat it as a secret until it has been run, and do not share it. The
# token is spent on first boot, and re-running this script afterwards will
# report that the device is already enrolled.
#
set -euo pipefail

THING="${thing}"
BUNDLE_URL="${url}"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

[ "$(id -u)" -eq 0 ] || { echo "Run this with sudo." >&2; exit 1; }

echo "Fetching the CamStream agent (${version}, ${platform})..."
if command -v curl >/dev/null 2>&1; then
  curl -fSL --retry 3 -o "$WORK/agent.tar.gz" "$BUNDLE_URL"
elif command -v wget >/dev/null 2>&1; then
  wget -q -O "$WORK/agent.tar.gz" "$BUNDLE_URL"
else
  echo "Neither curl nor wget is available." >&2
  exit 1
fi

tar -xzf "$WORK/agent.tar.gz" -C "$WORK"

# Written next to the bundle so install.sh can place it in the state directory.
cat > "$WORK/identity.json" <<'CAMSTREAM_IDENTITY'
${identity}
CAMSTREAM_IDENTITY
chmod 600 "$WORK/identity.json"

"$WORK/install.sh" --identity "$WORK/identity.json"
`;
}

function windowsScript(thing: string, identity: string, url: string, version: string): string {
  return `<#
  CamStream agent installer for ${thing}

  Generated by the admin console. This file contains a single-use enrollment
  token: treat it as a secret until it has been run. The token is spent on
  first boot, and re-running this afterwards reports the device as already
  enrolled.

  Run from an elevated PowerShell prompt.
#>
$ErrorActionPreference = 'Stop'

$Thing     = '${thing}'
$BundleUrl = '${url}'
$Work      = Join-Path $env:TEMP ("camstream-" + [guid]::NewGuid())

$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
if (-not (New-Object Security.Principal.WindowsPrincipal($identity)).IsInRole(
      [Security.Principal.WindowsBuiltInRole]::Administrator)) {
  throw 'Run this from an elevated PowerShell prompt.'
}

New-Item -ItemType Directory -Force -Path $Work | Out-Null
try {
  Write-Host "Fetching the CamStream agent (${version}, windows)..."
  Invoke-WebRequest -Uri $BundleUrl -OutFile "$Work\\agent.zip" -UseBasicParsing
  Expand-Archive -Path "$Work\\agent.zip" -DestinationPath $Work -Force

  $identityJson = @'
${identity}
'@
  Set-Content -Path "$Work\\identity.json" -Value $identityJson -Encoding UTF8

  & "$Work\\install.ps1" -IdentityPath "$Work\\identity.json"
} finally {
  Remove-Item -Recurse -Force $Work -ErrorAction SilentlyContinue
}
`;
}
