#!/usr/bin/env bash
# Refreshes the OUI vendor table the agent ships.
#
#   ./scripts/refresh-oui.sh
#
# The IEEE registry is the authority on which manufacturer owns the first
# three bytes of a MAC address. It is published as a 3.8MB CSV that is mostly
# postal addresses, so this keeps the two columns the agent uses and drops the
# rest, which is roughly a megabyte.
#
# The result is committed. An agent installs onto machines with no route to
# the internet, and a build must not depend on a third-party download.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/agent/src/main/resources/oui-vendors.csv"
SOURCE="${OUI_SOURCE_URL:-https://standards-oui.ieee.org/oui/oui.csv}"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

echo "Downloading $SOURCE ..."
curl -sS -L --max-time 300 -o "$TMP" "$SOURCE"

python3 - "$TMP" "$OUT" <<'PY'
import csv, sys, datetime

source, out = sys.argv[1], sys.argv[2]
rows = []
with open(source, newline='', encoding='utf-8-sig') as handle:
    for row in csv.DictReader(handle):
        oui = (row.get('Assignment') or '').strip().upper()
        name = ' '.join((row.get('Organization Name') or '').split())
        if len(oui) != 6 or not oui.isalnum() or not name:
            continue
        # A handful of registrations are withheld; a placeholder is worse than
        # no answer, because the console would show it as the vendor.
        if name.lower() in {'private', 'ieee registration authority'}:
            continue
        rows.append((oui, name[:64]))

rows.sort()
with open(out, 'w', newline='\n', encoding='utf-8') as handle:
    handle.write(f'# IEEE OUI assignments, trimmed to what the agent uses.\n')
    handle.write(f'# Generated by scripts/refresh-oui.sh on {datetime.date.today()}.\n')
    handle.write(f'# {len(rows)} assignments. Do not edit by hand.\n')
    writer = csv.writer(handle, lineterminator='\n')
    writer.writerow(['oui', 'organisation'])
    writer.writerows(rows)
print(f'{len(rows)} assignments written to {out}')
PY
